services:
  - type: web
    name: onlineshop
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn OnlineShop.wsgi"
    envVars:
      - key: DEBUG
        value: False
